cd vagrant-lamp-wordpress
vagrant up
cd ..
cd IdeaProjectsNew/ReleaseProject
mvn clean
mvn test
cd ..
cd ..
cd vagrant-lamp-wordpress
vagrant halt
cd ..
cd IdeaProjectsNew/ReleaseProject/target/surefire-reports
open emailable-report.html
